spring:
  profiles:
    active: dev
  application:
    name: user_management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_management?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  session:
    #失效时间
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    database: 0
    port: 6379
    host: 43.142.195.233
    password: 123321
  rabbitmq:
    host: 43.142.195.233
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto #表示消息确认方式，其有三种配置方式，分别是none、manual和auto；默认auto
        retry: #重试机制
          enabled: true #是否开启
          initial-interval: 1000 #重试间隔
          multiplier: 3 #对于上一次重试的乘数
          max-attempts: 4 #最大重试次数,默认3

server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag #全局删除逻辑的实体字段名
      logic-delete-value: 1 #逻辑未删除 1
      logic-not-delete-value: 0 #逻辑未删除 0





